
lang_eng = [
    "Arabic",
    "Bangla",
    "Bulgarian",
    "Bosnian",
    "Catalan",
    "Czech",
    "Danish",
    "German",
    "Estonian",
    "Greek",
    "Spanish",
    "Esperanto",
    "Basque",
    "Persian",
    "French",
    "Galician",
    "Korean",
    "Croatian",
    "Indonesian",
    "Italian",
    "Hebrew",
    "Georgian",
    "Latvian",
    "Lithuanian",
    "Hungarian",
    "Macedonian",
    "Malay",
    "Dutch",
    "Japanese",
    "Norwegian Bokmål",
    "Polish",
    "Portugese",
    "Romanian",
    "Russian",
    "English",
    "Slovak",
    "Slovenian",
    "Serbian",
    "Finnish",
    "Swedish",
    "Thai",
    "Turkish",
    "Ukranian",
    "Vietnamese",
    "Chinese"

]

# [Select language, Select, Wikipedia Article Comparison Tool, Compare, Select Comparison Tool, Select Similarity Percentage]

display_trans = {'Arabic': ['اختار اللغة:', 'يختار', 'أداة مقارنة مقالة ويكيبيديا', 'قارن', 'حدد أداة المقارنة:', 'حدد النسبة المئوية للتشابه:'], 
'Bangla': ['ভাষা নির্বাচন কর:', 'নির্বাচন করুন', 'উইকিপিডিয়া নিবন্ধ তুলনা সরঞ্জাম', 'তুলনা করা', 'তুলনা সরঞ্জাম নির্বাচন করুন:', 'সাদৃশ্য শতাংশ নির্বাচন করুন:'], 
'Basque': ['Hautatu Hizkuntza:', 'Hautatu', 'Wikipedia artikuluaren konparazio tresna', 'Alderatu', 'Hautatu Konparaziorako tresna:', 
'Aukeratu antzekotasun portzentajea:'], 'Bosnian': ['Odaberite Jezik:', 'Odabrati', 'Alat za upoređivanje članaka Wikipedia', 'Uporediti', 'Odaberite sredstvo za usporedbu:', 'Odaberite postotak sličnosti:'], 
'Bulgarian': ['Избери език:', 'Изберете', 'Инструмент за сравнение на статии в Уикипедия', 'Сравнете', 'Изберете инструмент за сравнение:', 'Изберете Процент на сходство:'], 
'Catalan': ["Escolliu l'idioma:", 'Seleccionar', "Eina de comparació de l'article de Viquipèdia", 'Comparar', "Seleccioneu l'eina de comparació:", 'Seleccioneu percentatge de similitud:'], 
'Chinese': ['选择语言：', '选择', 'Wikipedia文章比较工具', '相比', '选择比较工具：', '选择相似性百分比：'], 
'Croation': ['Izaberi jezik:', 'Odaberi', 'Wikipedia Alat za usporedbu članka', 'Usporediti', 'Odaberite Alat za usporedbu:', 'Odaberite postotak sličnosti:'], 
'Czech': ['Zvolte jazyk:', 'Vybrat', 'Nástroj pro srovnání článků Wikipedia', 'Porovnat', 'Vyberte Porovnání nástroje:', 'Vyberte procento podobnosti:'], 
'Danish': ['Vælg sprog:', 'Vælg', 'Wikipedia Artikel sammenligningsværktøj', 'Sammenligne', 'Vælg sammenligningsværktøj:', 'Vælg lighedsprocent:'], 
'Dutch': ['Selecteer taal:', 'Uitkiezen', 'Wikipedia artikelvergelijkingstool', 'Vergelijken', 'Selecteer Vergelijkingstool:', 'Selecteer gelijkenispercentage:'], 
'English': ['Select Language:', 'Select', 'Wikipedia Article Comparison Tool', 'Compare', 'Select comparison tool:', 'Select similarity percentage:'], 
'Esperanto': ['Elektu Lingvon:', 'Elektu', 'Vikipedio Artikola Kompara Ilo', 'Komparu', 'Elektu Kompara Ilo:', 'Elektu Similecan Procenton:'], 
'Estonian': ['Vali keel:', 'Valima', 'Vikipeedia artikli võrdlusvahend', 'Võrdlema', 'Valige võrdlusriist:', 'Valige sarnasuse protsent:'], 
'Finnish': ['Valitse kieli:', 'Valita', 'Wikipedia -artikkelin vertailutyökalu', 'Vertailla', 'Valitse vertailutyökalu:', 'Valitse samankaltaisuusprosentti:'], 
'French': ['Choisir la langue:', 'Sélectionner', "Outil de comparaison de l'article Wikipedia", 'Comparer', "Sélectionnez l'outil de comparaison:", 'Sélectionnez le pourcentage de similitude:'], 
'Galician': ['Selecciona Idioma:', 'Selecciona', 'Ferramenta de comparación de artigos de Wikipedia', 'Comparar', 'Seleccione Ferramenta de comparación:', 'Selecciona porcentaxe de semellanza:'], 
'Georgian': ['Აირჩიეთ ენა:', 'გადარჩევა', 'ვიკიპედიის სტატიის შედარების ინსტრუმენტი', 'შედარება', 'აირჩიეთ შედარების ინსტრუმენტი:', 'აირჩიეთ მსგავსების პროცენტი:'], 
'German': ['Sprache auswählen:', 'Auswählen', 'Wikipedia -Artikelvergleichsinstrument', 'Vergleichen', 'Wählen Sie Vergleichswerkzeug:', 'Wählen Sie Ähnlichkeitsprozentsatz:'], 
'Greek': ['Επιλέξτε γλώσσα:', 'Επιλέγω', 'Εργαλείο σύγκρισης άρθρων Wikipedia', 'Συγκρίνω', 'Επιλέξτε εργαλείο σύγκρισης:', 'Επιλέξτε Ποσοστό ομοιότητας:'], 
'Hebrew': ['בחר שפה:', 'בחר', 'כלי השוואת מאמרים בוויקיפדיה', 'לְהַשְׁווֹת', 'בחר בכלי השוואה:', 'בחר אחוז דמיון:'], 
'Hungarian': ['Válasszon nyelvet:', 'Válasszon', 'Wikipedia cikk összehasonlító eszköz', 'Összehasonlít', 'Válassza ki az összehasonlító eszközt:', 'Válassza ki a hasonlósági százalékot:'], 
'Indonesian': ['Pilih bahasa:', 'Pilih', 'Alat Perbandingan Artikel Wikipedia', 'Membandingkan', 'Pilih Alat Perbandingan:', 'Pilih persentase kesamaan:'], 
'Italian': ['Seleziona la lingua:', 'Selezionare', 'Strumento di confronto degli articoli di Wikipedia', 'Confrontare', 'Seleziona lo strumento di confronto:', 'Seleziona percentuale di somiglianza:'], 
'Japanese': ['言語を選択する：', '選択する', 'ウィキペディアの記事比較ツール', '比較', '比較ツールを選択します：', '類似性の割合を選択します：'], 
'Korean': ['언어 선택 :', '고르다', 'Wikipedia 기사 비교 도구', '비교하다', '비교 도구 선택 :', '유사성 백분율 선택 :'], 
'Latvian': ['Izvēlēties valodu:', 'Atlasīt', 'Wikipedia rakstu salīdzināšanas rīks', 'Salīdzināt', 'Atlasīt salīdzināšanas rīku:', 'Izvēlieties līdzības procentuālo daudzumu:'], 
'Lithuanian': ['Pasirinkite kalbą:', 'Pasirinkite', 'Vikipedijos straipsnių palyginimo įrankis', 'Palyginkite', 'Pasirinkite palyginimo įrankį:', 'Pasirinkite panašumo procentą:'], 
'Macedonian': ['Одбери јазик:', 'Изберете', 'Алатка за споредување на статии на Википедија', 'Споредете', 'Изберете алатка за споредување:', 'Изберете процент на сличност:'], 
'Malay': ['Pilih Bahasa:', 'Pilih', 'Alat Perbandingan Artikel Wikipedia', 'Bandingkan', 'Pilih Alat Perbandingan:', 'Pilih Peratusan Persamaan:'], 
'Norwegian': ['Velg språk:', 'Å velge', 'Wikipedia -artikkel Sammenligningsverktøy', 'Sammenligne', 'Velg sammenligningsverktøy:', 'Velg likhetsprosent:'], 
'Persian': ['زبان را انتخاب کنید:', 'انتخاب کنید', 'ابزار مقایسه مقاله ویکی پدیا', 'مقایسه کردن', 'ابزار مقایسه را انتخاب کنید:', 'درصد شباهت را انتخاب کنید:'], 
'Polish': ['Wybierz język:', 'Wybierz', 'Narzędzie do porównywania artykułów w Wikipedii', 'Porównywać', 'Wybierz narzędzie porównawcze:', 'Wybierz Procent podobieństwa:'], 
'Portugese': ['Selecione o idioma:', 'Selecione', 'Ferramenta de comparação de artigos da Wikipedia', 'Comparar', 'Selecione Ferramenta de comparação:', 'Selecione porcentagem de similaridade:'], 
'Romanian': ['Selecteaza limba:', 'Selectați', 'Instrument de comparare a articolului Wikipedia', 'Comparaţie', 'Selectați instrument de comparație:', 'Selectați procentul de similaritate:'], 
'Russian': ['Выберите язык:', 'Выбирать', 'Инструмент сравнения статей в Википедии', 'Сравнивать', 'Выберите инструмент сравнения:', 'Выберите процент сходства:'], 
'Serbian': ['Изаберите језик:', 'Одабрати', 'Алат за поређење чланака Википедије', 'Упоредити', 'Изаберите Алат за поређење:', 'Изаберите проценат сличности:'], 
'Slovak': ['Zvoľ jazyk:', 'Vybraný', 'Porovnanie článku Wikipedia', 'Porovnať', 'Vyberte porovnávací nástroj:', 'Vyberte percento podobnosti:'], 
'Slovenian': ['Izberi jezik:', 'Izberite', 'Orodje za primerjavo članka Wikipedije', 'Primerjaj', 'Izberite Primerjalno orodje:', 'Izberite Odstotek podobnosti:'], 
'Spanish': ['Seleccione el idioma:', 'Seleccione', 'Herramienta de comparación de artículos de Wikipedia', 'Comparar', 'Seleccione la herramienta de comparación:', 'Seleccionar porcentaje de similitud:'], 
'Swedish': ['Välj språk:', 'Välj', 'Wikipedia artikeljämförelseverktyg', 'Jämföra', 'Välj jämförelseverktyg:', 'Välj likhetsprocent:'], 
'Thai': ['เลือกภาษา:', 'เลือก', 'เครื่องมือเปรียบเทียบบทความ Wikipedia', 'เปรียบเทียบ', 'เลือกเครื่องมือเปรียบเทียบ:', 'เลือกเปอร์เซ็นต์ความคล้ายคลึงกัน:'], 
'Turkish': ['Dil Seçin:', 'Seçme', 'Wikipedia makale karşılaştırma aracı', 'Karşılaştırmak', 'Karşılaştırma aracını seçin:', 'Benzerlik yüzdesini seçin:'], 
'Ukranian': ['Оберіть мову:', 'Обраний', 'Інструмент порівняння статті Вікіпедії', 'Порівнювати', 'Виберіть інструмент порівняння:', 'Виберіть відсоток подібності:'], 
'Vietnamese': ['Chọn ngôn ngữ:', 'Lựa chọn', 'Công cụ so sánh bài viết Wikipedia', 'So sánh', 'Chọn Công cụ so sánh:', 'Chọn Tỷ lệ phần trăm tương tự:']}
   