import csv

text = dict()

# List of languages supported for GUI translation
lang_eng = [
    "العربية",
    "বাংলা",
    "Български",
    "Bosanski",
    "Català",
    "Čeština",
    "Dansk",
    "Deutsch",
    "Eesti",
    "Ελληνικά",
    "English",
    "Español",
    "Esperanto",
    "Euskara",
    "فارسی",
    "Français",
    "Galego",
    "한국어",
    "Hrvatski",
    "Bahasa Indonesia",
    "Italiano",
    "עברית",
    "ქართული",
    "Latviešu",
    "Lietuvių",
    "Magyar",
    "Македонски",
    "Bahasa Melayu",
    "Nederlands",
    "日本語",
    "Norsk",
    "Polski",
    "Português",
    "Română",
    "Русский",
    "Slovenčina",
    "Slovenščina",
    "Српски",
    "Suomi",
    "Svenska",
    "ไทย",
    "Türkçe",
    "Українська",
    "Tiếng Việt",
    "中文"

]

# [Select language, Select, Wikipedia Article Comparison Tool, Compare, Select Comparison Tool, Select Similarity Percentage]

# Open csv file that generated translations for application and create/print dictionary

#with open("display.csv") as file:
     #for line in csv.reader(file):
         #text[line[0]] = line[2:]


#print(text)

# UPDATE COMMENT: Dictionary of translations for application "of the screen"
display_trans = {
    "العربية": [
        "اختار اللغة:",
        "يختار",
        "أداة مقارنة مقالة ويكيبيديا",
        "قارن",
        "حدد أداة المقارنة:",
        "حدد النسبة المئوية للتشابه:",
        "يترجم",
        "صافي",
        "عدد الكلمات:",
        "نسبة التشابه:",
        "خطأ: لا يوجد نص في مربع المصدر!",
        "من أجل الترجمة ، هناك حاجة إلى نص في المربع المصدر بحيث يمكن ترجمة النص في المربع الهدف للمطابقة.",
        '"خطأ: الكثير من الأحرف"',
        "يتجاوز طول النص الذي تحاول ترجمته حد الأحرف 4500.",
        "مصدر",
        "استهداف",
        "دليل المستخدم"
    ],
    "বাংলা": [
        "ভাষা নির্বাচন কর:",
        "নির্বাচন করুন",
        "উইকিপিডিয়া নিবন্ধ তুলনা সরঞ্জাম",
        "তুলনা করা",
        "তুলনা সরঞ্জাম নির্বাচন করুন:",
        "সাদৃশ্য শতাংশ নির্বাচন করুন:",
        "অনুবাদ করা",
        "স্পষ্ট",
        "শব্দ গণনা:",
        "সাদৃশ্য শতাংশ:",
        "ত্রুটি: উত্স বাক্সে কোনও পাঠ্য নেই!",
        "অনুবাদ করার জন্য, উত্স বাক্সে পাঠ্য প্রয়োজন যাতে লক্ষ্য বাক্সের পাঠ্যটি মেলে অনুবাদ করা যায়।",
        '"ত্রুটি: অনেকগুলি অক্ষর"',
        "আপনি যে পাঠ্যটির দৈর্ঘ্য অনুবাদ করার চেষ্টা করছেন তা 4500 এর চরিত্রের সীমা ছাড়িয়ে গেছে।",
        "সূত্র",
        "লক্ষ্য",
        "ব্যবহারকারীর নির্দেশিকা"
    ],
    "Euskara": [
        "Hautatu Hizkuntza:",
        "Hautatu",
        "Wikipedia artikuluaren konparazio tresna",
        "Alderatu",
        "Hautatu Konparaziorako tresna:",
        "Aukeratu antzekotasun portzentajea:",
        "Itzuli",
        "Hustu",
        "Hitz kopurua:",
        "Antzekotasun portzentajea:",
        "ERROREA: ez da testurik iturburu-koadroan!",
        "Itzuli ahal izateko, testua behar da iturburu laukian, xede-koadroan testua bat datozen.",
        '"Errorea: pertsonaia gehiegi"',
        "Itzuli nahi duzun testuaren iraupena 4500 karaktere muga gainditzen du.",
        "Iturri",
        "Jomuga",
        "Erabiltzailearen Gidaliburua"
    ],
    "Bosanski": [
        "Odaberite Jezik:",
        "Odabrati",
        "Alat za upoređivanje članaka Wikipedia",
        "Uporediti",
        "Odaberite sredstvo za usporedbu:",
        "Odaberite postotak sličnosti:",
        "Prevesti",
        "Jasan",
        "Broj riječi:",
        "Procenat sličnosti:",
        "GREŠKA: Nema teksta u izvornom okviru!",
        "Da biste prevodili, tekst je potreban u izvornom okviru tako da se tekst u ciljnom okviru može prevesti na podudaranje.",
        '"Greška: previše znakova"',
        "Dužina teksta na koju pokušavate prevesti prelazi granicu znakova od 4500.",
        "Izvor",
        "Ciljati",
        "Korisnički vodič"
    ],
    "Български": [
        "Избери език:",
        "Изберете",
        "Инструмент за сравнение на статии в Уикипедия",
        "Сравнете",
        "Изберете инструмент за сравнение:",
        "Изберете Процент на сходство:",
        "Превод",
        "Ясно",
        "Брой думи:",
        "Процент на сходство:",
        "Грешка: Няма текст в полето Източник!",
        "За да се преведе, текстът е необходим в полето Източник, така че текстът в целевото поле да може да бъде преведен в съвпадение.",
        '"Грешка: Твърде много герои"',
        "Дължината на текста, която се опитвате да преведете, надвишава границата на символите от 4500.",
        "Източник",
        "Цел",
        "Упътване за употреба"
    ],
    "Català": [
        "Escolliu l'idioma:",
        "Seleccionar",
        "Eina de comparació de l'article de Viquipèdia",
        "Comparar",
        "Seleccioneu l'eina de comparació:",
        "Seleccioneu percentatge de similitud:",
        "Traduir",
        "Clar",
        "Nombre de paraules:",
        "Percentatge de similitud:",
        "Error: no hi ha text al quadre d'origen.",
        "Per traduir, es necessita text al quadre d'origen de manera que es pugui traduir el text del quadre de destinació.",
        '"Error: massa caràcters"',
        "La longitud del text que intenteu traduir supera el límit de caràcters de 4500.",
        "Font",
        "Objectiu",
        "Guia de l'usuari"
    ],
    "中文": [
        "选择语言：",
        "选择",
        "Wikipedia文章比较工具",
        "相比",
        "选择比较工具：",
        "选择相似性百分比：",
        "翻译",
        "清除",
        "字数：",
        "相似性百分比：",
        "错误：源框中没有文本！",
        "为了翻译，需要在源框中进行文本，以便可以将目标框中的文本翻译成匹配。",
        "“错误：太多字符”",
        "您试图翻译的文本长度超过了4500的字符限制。",
        "资源",
        "目标",
        "用户指南"
    ],
    "Hrvatski": [
        "Izaberi jezik:",
        "Odaberi",
        "Wikipedia Alat za usporedbu članka",
        "Usporediti",
        "Odaberite Alat za usporedbu:",
        "Odaberite postotak sličnosti:",
        "Prevedi",
        "Čisto",
        "Brojanje riječi:",
        "Postotak sličnosti:",
        "Pogreška: Nema teksta u izvornom okviru!",
        "Da bi se prevelo, tekst je potreban u izvornom okviru, tako da se tekst u okviru ciljanja može prevesti u podudaranje.",
        '"Pogreška: Previše znakova"',
        "Duljina teksta koji pokušavate prevesti premašuje granicu karaktera od 4500.",
        "Izvor",
        "Cilj",
        "Korisnički vodič"
    ],
    "Čeština": [
        "Zvolte jazyk:",
        "Vybrat",
        "Nástroj pro srovnání článků Wikipedia",
        "Porovnat",
        "Vyberte Porovnání nástroje:",
        "Vyberte procento podobnosti:",
        "přeložit",
        "Průhledná",
        "Počet slov:",
        "Procento podobnosti:",
        "Chyba: Žádný text ve zdrojovém poli!",
        "Aby bylo možné přeložit, je ve zdrojovém poli potřebný text, aby byl text v cílovém poli přeložen tak, aby odpovídal.",
        "„Chyba: příliš mnoho postav“",
        "Délka textu, který se snažíte přeložit, překračuje limit znaku 4500.",
        "Zdroj",
        "cílová",
        "Uživatelská příručka"
    ],
    "Dansk": [
        "Vælg sprog:",
        "Vælg",
        "Wikipedia Artikel sammenligningsværktøj",
        "Sammenligne",
        "Vælg sammenligningsværktøj:",
        "Vælg lighedsprocent:",
        "Oversætte",
        "Klar",
        "Ordtælling:",
        "Lighedsprocent:",
        "Fejl: Ingen tekst i kildeboksen!",
        "For at oversætte er der behov for tekst i kildeboksen, så teksten i målboksen kan oversættes til at matche.",
        '"Fejl: for mange tegn"',
        "Længden af tekst, du prøver at oversætte, overstiger karaktergrænsen på 4500.",
        "Kilde",
        "Mål",
        "Brugervejledning"
    ],
    "Nederlands": [
        "Selecteer taal:",
        "Uitkiezen",
        "Wikipedia artikelvergelijkingstool",
        "Vergelijken",
        "Selecteer Vergelijkingstool:",
        "Selecteer gelijkenispercentage:",
        "Vertalen",
        "Duidelijk",
        "Aantal woorden:",
        "Gelijkenispercentage:",
        "Fout: geen tekst in het bronbox!",
        "Om te vertalen, is tekst nodig in het bronvak zodat de tekst in het doelvak kan worden vertaald om te matchen.",
        '"Fout: te veel tekens"',
        "De lengte van de tekst die u probeert te vertalen overschrijdt de tekenlimiet van 4500.",
        "Bron",
        "Doelwit",
        "Gebruikershandleiding"
    ],
    "English": [
        "Select Language:",
        "Select",
        "Wikipedia Article Comparison Tool",
        "Compare",
        "Select comparison tool:",
        "Select similarity percentage:",
        "Translate",
        "Clear",
        "Word Count:",
        "Similarity Percentage:",
        "ERROR: NO TEXT IN SOURCE BOX!",
        "In order to translate, text is needed in the Source box so that the text in the Target box can be translated to match.",
        '"ERROR: Too many characters"',
        "The length of text you are trying to translate exceeds the character limit of 4500.",
        "Source",
        "Target",
        "User Guide"
    ],
    "Esperanto": [
        "Elektu Lingvon:",
        "Elektu",
        "Vikipedio Artikola Kompara Ilo",
        "Komparu",
        "Elektu Kompara Ilo:",
        "Elektu Similecan Procenton:",
        "Traduki",
        "Klara",
        "Sumo da vortoj:",
        "Simila Procento:",
        "Eraro: Neniu teksto en fontkesto!",
        "Por traduki, teksto necesas en la fontkesto por ke la teksto en la cela skatolo estu tradukita por kongrui.",
        '"Eraro: tro multaj signoj"',
        "La longeco de teksto, kiun vi provas traduki, superas la karakteron limo de 4500.",
        "Fonto",
        "Celo",
        "Uzantgvidilo"
    ],
    "Eesti": [
        "Vali keel:",
        "Valima",
        "Vikipeedia artikli võrdlusvahend",
        "Võrdlema",
        "Valige võrdlusriist:",
        "Valige sarnasuse protsent:",
        "Tõlkima",
        "Selge",
        "Sõnade arv:",
        "Sarnasuse protsent:",
        "Viga: lähtekastis pole teksti!",
        "Tõlkimiseks on lähtekarbis vaja teksti, nii et sihtkasti teksti saab tõlkida vastavalt sobivaks.",
        '"Viga: liiga palju märke"',
        "Teksti pikkus, mida proovite tõlkida, ületab tähemärgi piiri 4500.",
        "Allikas",
        "Siht",
        "Kasutusjuhend"
    ],
    "Suomi": [
        "Valitse kieli:",
        "Valita",
        "Wikipedia -artikkelin vertailutyökalu",
        "Vertailla",
        "Valitse vertailutyökalu:",
        "Valitse samankaltaisuusprosentti:",
        "Kääntää",
        "Asia selvä",
        "Sanamäärä:",
        "Samankaltaisuusprosentti:",
        "Virhe: Ei tekstiä lähdekotelossa!",
        "Kääntämiseksi tekstiä tarvitaan lähdealaatikkoon, jotta kohderuutuun teksti voidaan kääntää vastaamaan.",
        '"Virhe: liian monta merkkiä"',
        "Tekstin pituus, jonka yrität kääntää, ylittää merkkirajan 4500.",
        "Lähde",
        "Kohde",
        "Käyttöohjeet"
    ],
    "Français": [
        "Choisir la langue:",
        "Sélectionner",
        "Outil de comparaison de l'article de Wikipedia",
        "Comparer",
        "Sélectionnez l'outil de comparaison:",
        "Sélectionnez le pourcentage de similitude:",
        "Traduire",
        "Effacer",
        "Nombre de mots:",
        "Pourcentage de similitude:",
        "Erreur: pas de texte dans la boîte source!",
        "Pour traduire, le texte est nécessaire dans la zone source afin que le texte de la zone cible puisse être traduit pour correspondre.",
        '"Erreur: trop de caractères"',
        "La longueur du texte que vous essayez de traduire dépasse la limite de 4500 caractères.",
        "La source",
        "Cible",
        "Mode d'Emploi"
        "Article de Source"
    ],
    "Galego": [
        "Selecciona Idioma:",
        "Selecciona",
        "Ferramenta de comparación de artigos de Wikipedia",
        "Comparar",
        "Seleccione Ferramenta de comparación:",
        "Selecciona porcentaxe de semellanza:",
        "Traducir",
        "Claro",
        "Conta de palabras:",
        "Porcentaxe de semellanza:",
        "Erro: sen texto na caixa de orixe!",
        "Para traducir, é necesario un texto na caixa de orixe para que o texto da caixa de destino se poida traducir a coincidir.",
        '"Erro: demasiados personaxes"',
        "A lonxitude do texto que está intentando traducir supera o límite de caracteres de 4500.",
        "Fonte",
        "Obxectivo",
        "Guía do usuario"
    ],
    "ქართული": [
        "Აირჩიეთ ენა:",
        "გადარჩევა",
        "ვიკიპედიის სტატიის შედარების ინსტრუმენტი",
        "შედარება",
        "აირჩიეთ შედარების ინსტრუმენტი:",
        "აირჩიეთ მსგავსების პროცენტი:",
        "თარგმნა",
        "გასუფთავება",
        "სიტყვების დათვლა:",
        "მსგავსების პროცენტი:",
        "შეცდომა: არ არის ტექსტი წყაროს ყუთში!",
        "თარგმნის მიზნით, საჭიროა ტექსტი წყაროს ყუთში ისე, რომ სამიზნე ყუთში ტექსტის თარგმნა მოხდეს.",
        '"შეცდომა: ძალიან ბევრი სიმბოლო"',
        "ტექსტის სიგრძე, რომლის თარგმნასაც ცდილობთ, აღემატება პერსონაჟის ზღვარს 4500.",
        "წყარო",
        "სამიზნე",
        "მომხმარებლის სახელმძღვანელო"
    ],
    "Deutsch": [
        "Sprache auswählen:",
        "Auswählen",
        "Wikipedia -Artikelvergleichsinstrument",
        "Vergleichen",
        "Wählen Sie Vergleichswerkzeug:",
        "Wählen Sie Ähnlichkeitsprozentsatz:",
        "Übersetzen",
        "Klar",
        "Wortzahl:",
        "Ähnlichkeitsprozentsatz:",
        "Fehler: Kein Text im Quellfeld!",
        "Um übersetzt zu werden, wird im Quellfeld Text benötigt, damit der Text im Zielfeld in die Übereinstimmung übersetzt werden kann.",
        '"Fehler: Zu viele Zeichen"',
        "Die Länge des Textes, die Sie übersetzen möchten, überschreitet die Zeichengrenze von 4500.",
        "Quelle",
        "Ziel",
        "Benutzerhandbuch"
    ],
    "Ελληνικά": [
        "Επιλέξτε γλώσσα:",
        "Επιλέγω",
        "Εργαλείο σύγκρισης άρθρων Wikipedia",
        "Συγκρίνω",
        "Επιλέξτε εργαλείο σύγκρισης:",
        "Επιλέξτε Ποσοστό ομοιότητας:",
        "Μεταφράζω",
        "Σαφή",
        "Καταμέτρηση λέξεων:",
        "Ποσοστό ομοιότητας:",
        "Σφάλμα: Δεν υπάρχει κείμενο στο πλαίσιο πηγής!",
        "Προκειμένου να μεταφραστεί, απαιτείται κείμενο στο πλαίσιο πηγής έτσι ώστε το κείμενο στο πλαίσιο προορισμού να μπορεί να μεταφραστεί για να ταιριάζει.",
        '"Σφάλμα: Πάρα πολλοί χαρακτήρες"',
        "Το μήκος του κειμένου που προσπαθείτε να μεταφράσετε υπερβαίνει το όριο χαρακτήρων 4500.",
        "Πηγή",
        "Στόχος",
        "ΟΔΗΓΟΣ ΧΡΗΣΤΗ"
    ],
    "עברית": [
        "בחר שפה:",
        "בחר",
        "כלי השוואת מאמרים בוויקיפדיה",
        "לְהַשְׁווֹת",
        "בחר בכלי השוואה:",
        "בחר אחוז דמיון:",
        "תרגם",
        "ברור",
        "ספירת מילים:",
        "אחוז דמיון:",
        "שגיאה: אין טקסט בתיבת המקור!",
        "על מנת לתרגם, יש צורך בטקסט בתיבת המקור כך שניתן לתרגם את הטקסט בתיבת היעד כך שיתאים.",
        '"שגיאה: יותר מדי תווים"',
        "אורך הטקסט שאתה מנסה לתרגם עולה על גבול הדמות של 4500.",
        "מָקוֹר",
        "יַעַד",
        "מדריך למשתמש"
    ],
    "Magyar": [
        "Válasszon nyelvet:",
        "Válasszon",
        "Wikipedia cikk összehasonlító eszköz",
        "Összehasonlít",
        "Válassza ki az összehasonlító eszközt:",
        "Válassza ki a hasonlósági százalékot:",
        "fordít",
        "Egyértelmű",
        "Szavak száma:",
        "Hasonlósági százalék:",
        "Hiba: Nincs szöveg a forrás mezőben!",
        "A fordításhoz a forrásmezőben szövegesnek kell lennie, hogy a cél mezőben lévő szöveg lefordítható legyen.",
        '"Hiba: Túl sok karakter"',
        "A lefordítani kívánt szöveg hossza meghaladja a 4500 karakterhatárot.",
        "Forrás",
        "Cél",
        "Használati útmutató"
    ],
    "Bahasa Indonesia": [
        "Pilih bahasa:",
        "Pilih",
        "Alat Perbandingan Artikel Wikipedia",
        "Membandingkan",
        "Pilih Alat Perbandingan:",
        "Pilih persentase kesamaan:",
        "Menerjemahkan",
        "Jernih",
        "Jumlah kata:",
        "Persentase kesamaan:",
        "Kesalahan: Tidak ada teks di kotak sumber!",
        "Untuk menerjemahkan, teks diperlukan di kotak sumber sehingga teks di kotak target dapat diterjemahkan agar cocok.",
        '"Kesalahan: terlalu banyak karakter"',
        "Panjang teks yang Anda coba terjemahkan melebihi batas karakter 4500.",
        "Sumber",
        "Target",
        "Panduan pengguna"
    ],
    "Italiano": [
        "Seleziona la lingua:",
        "Selezionare",
        "Strumento di confronto degli articoli di Wikipedia",
        "Confrontare",
        "Seleziona lo strumento di confronto:",
        "Seleziona percentuale di somiglianza:",
        "Tradurre",
        "Chiaro",
        "Conteggio delle parole:",
        "Percentuale di somiglianza:",
        "Errore: nessun testo nella casella di origine!",
        "Per tradurre, è necessario un testo nella casella di origine in modo che il testo nella casella di destinazione possa essere tradotto in modo da abbinare.",
        '"Errore: troppi caratteri"',
        "La lunghezza del testo che stai cercando di tradurre supera il limite di carattere di 4500.",
        "Fonte",
        "Obbiettivo",
        "Guida utente"
    ],
    "日本語": [
        "言語を選択する：",
        "選択する",
        "ウィキペディアの記事比較ツール",
        "比較",
        "比較ツールを選択します：",
        "類似性の割合を選択します：",
        "翻訳",
        "クリア",
        "単語数：",
        "類似性率：",
        "エラー：ソースボックスにテキストはありません！",
        "翻訳するには、ターゲットボックスのテキストを一致するように翻訳できるように、ソースボックスにテキストが必要です。",
        "「エラー：文字が多すぎる」",
        "翻訳しようとしているテキストの長さは、4500の文字制限を超えています。",
        "ソース",
        "目標",
        "ユーザーガイド"
    ],
    "한국어": [
        "언어 선택 :",
        "고르다",
        "Wikipedia 기사 비교 도구",
        "비교하다",
        "비교 도구 선택 :",
        "유사성 백분율 선택 :",
        "번역하다",
        "분명한",
        "단어 수:",
        "유사성 백분율 :",
        "오류 : 소스 상자에 텍스트가 없습니다!",
        "번역하려면 대상 상자의 텍스트를 일치하도록 번역 할 수 있도록 소스 상자에 텍스트가 필요합니다.",
        '"오류 : 너무 많은 문자"',
        "번역하려는 텍스트 길이는 4500의 문자 한계를 초과합니다.",
        "원천",
        "표적",
        "사용자 설명서"
    ],
    "Latviešu": [
        "Izvēlēties valodu:",
        "Atlasīt",
        "Wikipedia rakstu salīdzināšanas rīks",
        "Salīdzināt",
        "Atlasīt salīdzināšanas rīku:",
        "Izvēlieties līdzības procentuālo daudzumu:",
        "Tulkot",
        "Noskaidrot",
        "Vārdu skaits:",
        "Līdzības procents:",
        "Kļūda: Avota lodziņā nav teksta!",
        "Lai tulkotu, avota lodziņā ir nepieciešams teksts, lai mērķa lodziņa tekstu varētu tulkot atbilstoši.",
        '"Kļūda: pārāk daudz rakstzīmju"',
        "Jūsu mēģinātā teksta garums pārsniedz rakstzīmju ierobežojumu 4500.",
        "Avots",
        "Tēlot",
        "Lietotāja rokasgrāmata"
    ],
    "Lietuvių": [
        "Pasirinkite kalbą:",
        "Pasirinkite",
        "Vikipedijos straipsnių palyginimo įrankis",
        "Palyginkite",
        "Pasirinkite palyginimo įrankį:",
        "Pasirinkite panašumo procentą:",
        "Išversti",
        "Aišku",
        "Žodžių skaičius:",
        "Panašumo procentas:",
        "Klaida: Šaltinio laukelyje nėra teksto!",
        "Norint išversti, šaltinio laukelyje reikia teksto, kad tikslinio laukelio tekstas būtų išverstas taip, kad atitiktų.",
        '"Klaida: per daug simbolių"',
        "Teksto ilgis, kurį bandote išversti, viršija 4500 simbolių limitą.",
        "Šaltinis",
        "Taikinys",
        "Naudotojo gidas"
    ],
    "Македонски": [
        "Одбери јазик:",
        "Изберете",
        "Алатка за споредување на статии на Википедија",
        "Споредете",
        "Изберете алатка за споредување:",
        "Изберете процент на сличност:",
        "Преведете",
        "Чиста",
        "Бројот на зборови:",
        "Процент на сличност:",
        "Грешка: Нема текст во изворното поле!",
        "За да се преведе, потребен е текст во изворното поле, така што текстот во целната кутија може да се преведе за да одговара.",
        "„Грешка: премногу карактери“",
        "Должината на текстот што се обидувате да го преведете го надминува границата на знакот од 4500.",
        "Извор",
        "Цел",
        "Упатство за корисникот"
    ],
    "Bahasa Melayu": [
        "Pilih Bahasa:",
        "Pilih",
        "Alat Perbandingan Artikel Wikipedia",
        "Bandingkan",
        "Pilih Alat Perbandingan:",
        "Pilih Peratusan Persamaan:",
        "Terjemahkan",
        "Jelas",
        "Kiraan perkataan:",
        "Peratusan Persamaan:",
        "Ralat: Tiada teks dalam kotak sumber!",
        "Untuk diterjemahkan, teks diperlukan dalam kotak sumber supaya teks dalam kotak sasaran dapat diterjemahkan untuk dipadankan.",
        '"Ralat: Terlalu banyak watak"',
        "Panjang teks yang anda cuba diterjemahkan melebihi had aksara 4500.",
        "Sumber",
        "Sasaran",
        "Panduan pengguna"
    ],
    "Norsk": [
        "Velg språk:",
        "Å velge",
        "Wikipedia -artikkel Sammenligningsverktøy",
        "Sammenligne",
        "Velg sammenligningsverktøy:",
        "Velg likhetsprosent:",
        "Oversette",
        "Klar",
        "Ordtelling:",
        "Likhetsprosent:",
        "Feil: Ingen tekst i kildeboksen!",
        "For å oversette er det nødvendig med tekst i kildeboksen slik at teksten i målboksen kan oversettes for å matche.",
        '"Feil: for mange tegn"',
        "Tekstens lengde du prøver å oversette overstiger karaktergrensen på 4500.",
        "Kilde",
        "Mål",
        "Brukerhåndboken"
    ],
    "فارسی": [
        "زبان را انتخاب کنید:",
        "انتخاب کنید",
        "ابزار مقایسه مقاله ویکی پدیا",
        "مقایسه کردن",
        "ابزار مقایسه را انتخاب کنید:",
        "درصد شباهت را انتخاب کنید:",
        "ترجمه کردن",
        "پاک کردن",
        "تعداد کلمه:",
        "درصد شباهت:",
        "خطا: بدون متن در جعبه منبع!",
        "به منظور ترجمه ، متن در جعبه منبع مورد نیاز است تا متن موجود در جعبه هدف برای مطابقت با آن ترجمه شود.",
        '"خطا: شخصیت های زیادی"',
        "طول متنی که می خواهید ترجمه کنید بیش از حد شخصیت 4500 است.",
        "منبع",
        "هدف",
        "راهنمای کاربر"
    ],
    "Polski": [
        "Wybierz język:",
        "Wybierz",
        "Narzędzie do porównywania artykułów w Wikipedii",
        "Porównywać",
        "Wybierz narzędzie porównawcze:",
        "Wybierz Procent podobieństwa:",
        "Tłumaczyć",
        "Jasne",
        "Liczba słów:",
        "Procent podobieństwa:",
        "Błąd: brak tekstu w polu źródłowym!",
        "Aby przetłumaczyć, tekst jest potrzebny w polu źródłowym, aby tekst w polu docelowym można było przetłumaczyć do dopasowania.",
        "„Błąd: zbyt wiele znaków”",
        "Długość tekstu, którą próbujesz przetłumaczyć, przekracza limit znaków 4500.",
        "Źródło",
        "Cel",
        "Podręcznik użytkownika"
    ],
    "Português": [
        "Selecione o idioma:",
        "Selecione",
        "Ferramenta de comparação de artigos da Wikipedia",
        "Comparar",
        "Selecione Ferramenta de comparação:",
        "Selecione porcentagem de similaridade:",
        "Traduzir",
        "Claro",
        "Contagem de palavras:",
        "Porcentagem de similaridade:",
        "Erro: nenhum texto na caixa de origem!",
        "Para traduzir, é necessário texto na caixa de origem para que o texto na caixa de destino possa ser traduzido para corresponder.",
        '"Erro: muitos personagens"',
        "O comprimento do texto que você está tentando traduzir excede o limite do caractere de 4500.",
        "Fonte",
        "Alvo",
        "Podręcznik użytkownika"
    ],
    "Română": [
        "Selecteaza limba:",
        "Selectați",
        "Instrument de comparare a articolului Wikipedia",
        "Comparaţie",
        "Selectați instrument de comparație:",
        "Selectați procentul de similaritate:",
        "Traduceți",
        "clar",
        "Număr de cuvinte:",
        "Procent de similaritate:",
        "Eroare: Fără text în caseta sursă!",
        "Pentru a traduce, textul este necesar în caseta sursă, astfel încât textul din caseta țintă să poată fi tradus pentru a se potrivi.",
        "„Eroare: prea multe personaje”",
        "Lungimea textului pe care încercați să o traduceți depășește limita de caracter de 4500.",
        "Sursă",
        "Ţintă",
        "Manualul utilizatorului"
    ],
    "Русский": [
        "Выберите язык:",
        "Выбирать",
        "Инструмент сравнения статей в Википедии",
        "Сравнивать",
        "Выберите инструмент сравнения:",
        "Выберите процент сходства:",
        "Перевести",
        "чистый",
        "Количество слов:",
        "Процент сходства:",
        "Ошибка: нет текста в исходном поле!",
        "Чтобы перевести, в исходном поле необходим текст, чтобы текст в целевом поле можно было перевести, чтобы соответствовать.",
        '"Ошибка: слишком много символов"',
        "Длина текста, который вы пытаетесь перевести, превышает предел символа 4500.",
        "Источник",
        "Цель",
        "Гид пользователя"
    ],
    "Српски": [
        "Изаберите језик:",
        "Одабрати",
        "Алат за поређење чланака Википедије",
        "Упоредити",
        "Изаберите Алат за поређење:",
        "Изаберите проценат сличности:",
        "превести",
        "Јасно",
        "Број речи:",
        "Проценат сличности:",
        "Грешка: Нема текста у изворном пољу!",
        "Да би се преводио, потребан је текст у изворном оквиру тако да се текст у циљаној кутији може превести на подударање.",
        '"Грешка: Превише знакова"',
        "Дужина текста који покушавате да преведете прелази ограничење знака од 4500.",
        "Извор",
        "Мета",
        "Упутство за употребу"
    ],
    "Slovenčina": [
        "Zvoľ jazyk:",
        "Vybraný",
        "Porovnanie článku Wikipedia",
        "Porovnať",
        "Vyberte porovnávací nástroj:",
        "Vyberte percento podobnosti:",
        "Preložiť",
        "jasný",
        "Počet slov:",
        "Percento podobnosti:",
        "Chyba: Žiadny text v zdrojovom políčku!",
        "Na preklad je v zdrojovom políčku potrebný text, takže text v cieľovom políčku je možné preložiť tak, aby sa zhodoval.",
        "„Chyba: Príliš veľa znakov“",
        "Dĺžka textu, ktorý sa snažíte preložiť, presahuje limit znakov 4500.",
        "Zdroj",
        "Cieľ",
        "Užívateľská príručka"
    ],
    "Slovenščina": [
        "Izberi jezik:",
        "Izberite",
        "Orodje za primerjavo članka Wikipedije",
        "Primerjaj",
        "Izberite Primerjalno orodje:",
        "Izberite Odstotek podobnosti:",
        "Prevesti",
        "Jasno",
        "Število besed:",
        "Odstotek podobnosti:",
        "Napaka: Brez besedila v izvornem polju!",
        "Za prevajanje je v izvornem polju potrebno besedilo, tako da se besedilo v ciljnem polju lahko prevede na ujemanje.",
        '"Napaka: preveč znakov"',
        "Dolžina besedila, ki ga poskušate prevesti, presega mejo znakov 4500.",
        "Vir",
        "Cilj",
        "Navodila"
    ],
    "Español": [
        "Seleccione el idioma:",
        "Seleccione",
        "Herramienta de comparación de artículos de Wikipedia",
        "Comparar",
        "Seleccione la herramienta de comparación:",
        "Seleccionar porcentaje de similitud:",
        "Traducir",
        "Claro",
        "El recuento de palabras:",
        "Porcentaje de similitud:",
        "Error: ¡No hay texto en el cuadro fuente!",
        "Para traducirse, se necesita texto en el cuadro de origen para que el texto en el cuadro de destino se pueda traducir para que coincida.",
        '"Error: demasiados personajes"',
        "La longitud del texto que está tratando de traducir excede el límite de caracteres de 4500.",
        "Fuente",
        "Objetivo",
        "Guía del usuario"
    ],
    "Svenska": [
        "Välj språk:",
        "Välj",
        "Wikipedia artikeljämförelseverktyg",
        "Jämföra",
        "Välj jämförelseverktyg:",
        "Välj likhetsprocent:",
        "Översätt",
        "Klar",
        "Antal ord:",
        "Likhetsprocent:",
        "Fel: Ingen text i källrutan!",
        "För att översätta behövs text i källrutan så att texten i målrutan kan översättas till matchning.",
        '"Fel: för många karaktärer"',
        "Längden på text du försöker översätta överskrider teckengränsen på 4500.",
        "Källa",
        "Mål",
        "Användarguide"
    ],
    "ไทย": [
        "เลือกภาษา:",
        "เลือก",
        "เครื่องมือเปรียบเทียบบทความ Wikipedia",
        "เปรียบเทียบ",
        "เลือกเครื่องมือเปรียบเทียบ:",
        "เลือกเปอร์เซ็นต์ความคล้ายคลึงกัน:",
        "แปลภาษา",
        "ชัดเจน",
        "การนับจำนวนคำ:",
        "เปอร์เซ็นต์ความคล้ายคลึงกัน:",
        "ข้อผิดพลาด: ไม่มีข้อความในกล่องต้นทาง!",
        "ในการแปลจำเป็นต้องมีข้อความในกล่องต้นทางเพื่อให้ข้อความในกล่องเป้าหมายสามารถแปลให้ตรงกัน",
        '"ข้อผิดพลาด: อักขระมากเกินไป"',
        "ความยาวของข้อความที่คุณพยายามแปลเกินขีด จำกัด อักขระ 4,500",
        "แหล่งที่มา",
        "เป้า",
        "คู่มือผู้ใช้"
    ],
    "Türkçe": [
        "Dil Seçin:",
        "Seçme",
        "Wikipedia makale karşılaştırma aracı",
        "Karşılaştırmak",
        "Karşılaştırma aracını seçin:",
        "Benzerlik yüzdesini seçin:",
        "Çevirmek",
        "Temizlemek",
        "Sözcük sayısı:",
        "Benzerlik yüzdesi:",
        "Hata: Kaynak kutusunda metin yok!",
        "Tercüme etmek için, hedef kutudaki metin eşleşecek şekilde çevrilebilmesi için kaynak kutusunda metin gereklidir.",
        '"Hata: Çok fazla karakter"',
        "Çevirmeye çalıştığınız metnin uzunluğu 4500 karakter sınırını aşar.",
        "Kaynak",
        "Hedef",
        "Kullanici rehberi"
    ],
    "Українська": [
        "Оберіть мову:",
        "Обраний",
        "Інструмент порівняння статті Вікіпедії",
        "Порівнювати",
        "Виберіть інструмент порівняння:",
        "Виберіть відсоток подібності:",
        "Перекладати",
        "Чіткий",
        "Підрахунок слів:",
        "Відсоток подібності:",
        "Помилка: Немає тексту у вікні джерела!",
        "Для перекладу потрібний текст у вікні Source, щоб текст у поле Target можна було перекласти на відповідність.",
        '"Помилка: занадто багато символів"',
        "Довжина тексту, який ви намагаєтесь перекласти, перевищує межу символу 4500.",
        "Джерело",
        "Цільовий",
        "Керівництво користувача"
    ],
    "Tiếng Việt": [
        "Chọn ngôn ngữ:",
        "Lựa chọn",
        "Công cụ so sánh bài viết Wikipedia",
        "So sánh",
        "Chọn Công cụ so sánh:",
        "Chọn Tỷ lệ phần trăm tương tự:",
        "Dịch",
        "Xa lạ",
        "Số từ:",
        "Tỷ lệ tương tự:",
        "Lỗi: Không có văn bản trong hộp nguồn!",
        "Để dịch, văn bản là cần thiết trong hộp nguồn để văn bản trong hộp đích có thể được dịch để khớp.",
        '"Lỗi: Quá nhiều ký tự"',
        "Độ dài của văn bản bạn đang cố gắng dịch vượt quá giới hạn ký tự là 4500.",
        "Nguồn",
        "Mục tiêu",
        "Hướng dẫn sử dụng"
    ],
}
