
lang_eng = [
    "العربية",
    "বাংলা",
    "Български",
    "Bosanski",
    "Català",
    "Čeština",
    "Dansk",
    "Deutsch",
    "Eesti",
    "Ελληνικά",
    "English",
    "Español",
    "Esperanto",
    "Euskara",
    "فارسی",
    "Français",
    "Galego",
    "한국어",
    "Hrvatski",
    "Bahasa Indonesia",
    "Italiano",
    "עברית",
    "ქართული",
    "Latviešu",
    "Lietuvių",
    "Magyar",
    "Македонски",
    "Bahasa Melayu",
    "Nederlands",
    "日本語",
    "Norsk",
    "Polski",
    "Português",
    "Română",
    "Русский",
    "Slovenčina",
    "Slovenščina",
    "Српски / srpski",
    "Suomi",
    "Swedish",
    "ไทย",
    "Türkçe",
    "Українська",
    "Tiếng Việt",
    "中文"

]

# [Select language, Select, Wikipedia Article Comparison Tool, Compare, Select Comparison Tool, Select Similarity Percentage]

display_trans = {
'العربية': ['اختار اللغة:', 'يختار', 'أداة مقارنة مقالة ويكيبيديا', 'قارن', 'حدد أداة المقارنة:', 'حدد النسبة المئوية للتشابه:'], 
'বাংলা': ['ভাষা নির্বাচন কর:', 'নির্বাচন করুন', 'উইকিপিডিয়া নিবন্ধ তুলনা সরঞ্জাম', 'তুলনা করা', 'তুলনা সরঞ্জাম নির্বাচন করুন:', 'সাদৃশ্য শতাংশ নির্বাচন করুন:'], 
'Euskara': ['Hautatu Hizkuntza:', 'Hautatu', 'Wikipedia artikuluaren konparazio tresna', 'Alderatu', 'Hautatu Konparaziorako tresna:', 
'Aukeratu antzekotasun portzentajea:'], 
'Bosanski': ['Odaberite Jezik:', 'Odabrati', 'Alat za upoređivanje članaka Wikipedia', 'Uporediti', 'Odaberite sredstvo za usporedbu:', 'Odaberite postotak sličnosti:'], 
'Български': ['Избери език:', 'Изберете', 'Инструмент за сравнение на статии в Уикипедия', 'Сравнете', 'Изберете инструмент за сравнение:', 'Изберете Процент на сходство:'], 
'Català': ["Escolliu l'idioma:", 'Seleccionar', "Eina de comparació de l'article de Viquipèdia", 'Comparar', "Seleccioneu l'eina de comparació:", 'Seleccioneu percentatge de similitud:'], 
'中文': ['选择语言：', '选择', 'Wikipedia文章比较工具', '相比', '选择比较工具：', '选择相似性百分比：'], 
'Hrvatski': ['Izaberi jezik:', 'Odaberi', 'Wikipedia Alat za usporedbu članka', 'Usporediti', 'Odaberite Alat za usporedbu:', 'Odaberite postotak sličnosti:'], 
'Čeština': ['Zvolte jazyk:', 'Vybrat', 'Nástroj pro srovnání článků Wikipedia', 'Porovnat', 'Vyberte Porovnání nástroje:', 'Vyberte procento podobnosti:'], 
'Dansk': ['Vælg sprog:', 'Vælg', 'Wikipedia Artikel sammenligningsværktøj', 'Sammenligne', 'Vælg sammenligningsværktøj:', 'Vælg lighedsprocent:'], 
'Nederlands': ['Selecteer taal:', 'Uitkiezen', 'Wikipedia artikelvergelijkingstool', 'Vergelijken', 'Selecteer Vergelijkingstool:', 'Selecteer gelijkenispercentage:'], 
'English': ['Select Language:', 'Select', 'Wikipedia Article Comparison Tool', 'Compare', 'Select comparison tool:', 'Select similarity percentage:'], 
'Esperanto': ['Elektu Lingvon:', 'Elektu', 'Vikipedio Artikola Kompara Ilo', 'Komparu', 'Elektu Kompara Ilo:', 'Elektu Similecan Procenton:'], 
'Eesti': ['Vali keel:', 'Valima', 'Vikipeedia artikli võrdlusvahend', 'Võrdlema', 'Valige võrdlusriist:', 'Valige sarnasuse protsent:'], 
'Suomi': ['Valitse kieli:', 'Valita', 'Wikipedia -artikkelin vertailutyökalu', 'Vertailla', 'Valitse vertailutyökalu:', 'Valitse samankaltaisuusprosentti:'], 
'Français': ['Choisir la langue:', 'Sélectionner', "Outil de comparaison de l'article Wikipedia", 'Comparer', "Sélectionnez l'outil de comparaison:", 'Sélectionnez le pourcentage de similitude:'], 
'Galego': ['Selecciona Idioma:', 'Selecciona', 'Ferramenta de comparación de artigos de Wikipedia', 'Comparar', 'Seleccione Ferramenta de comparación:', 'Selecciona porcentaxe de semellanza:'], 
'ქართული': ['Აირჩიეთ ენა:', 'გადარჩევა', 'ვიკიპედიის სტატიის შედარების ინსტრუმენტი', 'შედარება', 'აირჩიეთ შედარების ინსტრუმენტი:', 'აირჩიეთ მსგავსების პროცენტი:'], 
'Deutsch': ['Sprache auswählen:', 'Auswählen', 'Wikipedia -Artikelvergleichsinstrument', 'Vergleichen', 'Wählen Sie Vergleichswerkzeug:', 'Wählen Sie Ähnlichkeitsprozentsatz:'], 
'Ελληνικά': ['Επιλέξτε γλώσσα:', 'Επιλέγω', 'Εργαλείο σύγκρισης άρθρων Wikipedia', 'Συγκρίνω', 'Επιλέξτε εργαλείο σύγκρισης:', 'Επιλέξτε Ποσοστό ομοιότητας:'], 
'עברית': ['בחר שפה:', 'בחר', 'כלי השוואת מאמרים בוויקיפדיה', 'לְהַשְׁווֹת', 'בחר בכלי השוואה:', 'בחר אחוז דמיון:'], 
'Magyar': ['Válasszon nyelvet:', 'Válasszon', 'Wikipedia cikk összehasonlító eszköz', 'Összehasonlít', 'Válassza ki az összehasonlító eszközt:', 'Válassza ki a hasonlósági százalékot:'], 
'Bahasa Indonesia': ['Pilih bahasa:', 'Pilih', 'Alat Perbandingan Artikel Wikipedia', 'Membandingkan', 'Pilih Alat Perbandingan:', 'Pilih persentase kesamaan:'], 
'Italiano': ['Seleziona la lingua:', 'Selezionare', 'Strumento di confronto degli articoli di Wikipedia', 'Confrontare', 'Seleziona lo strumento di confronto:', 'Seleziona percentuale di somiglianza:'], 
'Japanese': ['言語を選択する：', '選択する', 'ウィキペディアの記事比較ツール', '比較', '比較ツールを選択します：', '類似性の割合を選択します：'], 
'한국어': ['언어 선택 :', '고르다', 'Wikipedia 기사 비교 도구', '비교하다', '비교 도구 선택 :', '유사성 백분율 선택 :'], 
'Latviešu': ['Izvēlēties valodu:', 'Atlasīt', 'Wikipedia rakstu salīdzināšanas rīks', 'Salīdzināt', 'Atlasīt salīdzināšanas rīku:', 'Izvēlieties līdzības procentuālo daudzumu:'], 
'Lietuvių': ['Pasirinkite kalbą:', 'Pasirinkite', 'Vikipedijos straipsnių palyginimo įrankis', 'Palyginkite', 'Pasirinkite palyginimo įrankį:', 'Pasirinkite panašumo procentą:'], 
'Македонски': ['Одбери јазик:', 'Изберете', 'Алатка за споредување на статии на Википедија', 'Споредете', 'Изберете алатка за споредување:', 'Изберете процент на сличност:'], 
'Bahasa Melayu': ['Pilih Bahasa:', 'Pilih', 'Alat Perbandingan Artikel Wikipedia', 'Bandingkan', 'Pilih Alat Perbandingan:', 'Pilih Peratusan Persamaan:'], 
'Norsk': ['Velg språk:', 'Å velge', 'Wikipedia -artikkel Sammenligningsverktøy', 'Sammenligne', 'Velg sammenligningsverktøy:', 'Velg likhetsprosent:'], 
'فارسی': ['زبان را انتخاب کنید:', 'انتخاب کنید', 'ابزار مقایسه مقاله ویکی پدیا', 'مقایسه کردن', 'ابزار مقایسه را انتخاب کنید:', 'درصد شباهت را انتخاب کنید:'], 
'Polish': ['Wybierz język:', 'Wybierz', 'Narzędzie do porównywania artykułów w Wikipedii', 'Porównywać', 'Wybierz narzędzie porównawcze:', 'Wybierz Procent podobieństwa:'], 
'Português': ['Selecione o idioma:', 'Selecione', 'Ferramenta de comparação de artigos da Wikipedia', 'Comparar', 'Selecione Ferramenta de comparação:', 'Selecione porcentagem de similaridade:'], 
'Română': ['Selecteaza limba:', 'Selectați', 'Instrument de comparare a articolului Wikipedia', 'Comparaţie', 'Selectați instrument de comparație:', 'Selectați procentul de similaritate:'], 
'Русский': ['Выберите язык:', 'Выбирать', 'Инструмент сравнения статей в Википедии', 'Сравнивать', 'Выберите инструмент сравнения:', 'Выберите процент сходства:'], 
'Српски / srpski': ['Изаберите језик:', 'Одабрати', 'Алат за поређење чланака Википедије', 'Упоредити', 'Изаберите Алат за поређење:', 'Изаберите проценат сличности:'], 
'Slovenčina': ['Zvoľ jazyk:', 'Vybraný', 'Porovnanie článku Wikipedia', 'Porovnať', 'Vyberte porovnávací nástroj:', 'Vyberte percento podobnosti:'], 
'Slovenščina': ['Izberi jezik:', 'Izberite', 'Orodje za primerjavo članka Wikipedije', 'Primerjaj', 'Izberite Primerjalno orodje:', 'Izberite Odstotek podobnosti:'], 
'Español': ['Seleccione el idioma:', 'Seleccione', 'Herramienta de comparación de artículos de Wikipedia', 'Comparar', 'Seleccione la herramienta de comparación:', 'Seleccionar porcentaje de similitud:'], 
'Svenska': ['Välj språk:', 'Välj', 'Wikipedia artikeljämförelseverktyg', 'Jämföra', 'Välj jämförelseverktyg:', 'Välj likhetsprocent:'], 
'ไทย': ['เลือกภาษา:', 'เลือก', 'เครื่องมือเปรียบเทียบบทความ Wikipedia', 'เปรียบเทียบ', 'เลือกเครื่องมือเปรียบเทียบ:', 'เลือกเปอร์เซ็นต์ความคล้ายคลึงกัน:'], 
'Türkçe': ['Dil Seçin:', 'Seçme', 'Wikipedia makale karşılaştırma aracı', 'Karşılaştırmak', 'Karşılaştırma aracını seçin:', 'Benzerlik yüzdesini seçin:'], 
'Українська': ['Оберіть мову:', 'Обраний', 'Інструмент порівняння статті Вікіпедії', 'Порівнювати', 'Виберіть інструмент порівняння:', 'Виберіть відсоток подібності:'], 
'Tiếng Việt': ['Chọn ngôn ngữ:', 'Lựa chọn', 'Công cụ so sánh bài viết Wikipedia', 'So sánh', 'Chọn Công cụ so sánh:', 'Chọn Tỷ lệ phần trăm tương tự:']}
   